---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: volley
  annotations:
    fluxcd.io/automated: "true"
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: volley
    spec:
      containers:
      - name: volley
        # image: 00000000000000.dkr.ecr.my-region.amazonaws.com/example-eks:tag
        image: REGISTRY/IMAGE:TAG
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 250m
          limits:
            cpu: 500m