---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: volley
  annotations:
    fluxcd.io/automated: "true"
spec:
  replicas: 3
  selector:
    matchLabels:
      app: volley
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: volley
    spec:
      containers:
      - name: volley
        # image: 00000000000000.dkr.ecr.my-region.amazonaws.com/example-eks:tag
        image: drazer/volleypractice:de85bd644331c457d0aa840a3eeb6e515a9398c8
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 250m
          limits:
            cpu: 500m
